steps:
  - name: 'node:12-alpine'
    entrypoint: npm
    args:
      - 'install'
  - name: 'node:12-alpine'
    entrypoint: npm
    args:
      - 'test'
  - name: 'docker:stable'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '.'
  - name: 'docker:stable'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - name: 'google/cloud-sdk:alpine'
    args:
      - gcloud
      - 'run'
      - 'deploy'
      - '$REPO_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME
  